# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuU5epxqxGbSb3WnUwjcI1rldKZYZy1j
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload the image
print("Upload a grayscale image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
# Step 2: Read the image in grayscale
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

40

# Step 3: Apply negative transformation
negative = 255 - img
# Step 4: Display results using matplotlib
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(negative, cmap='gray')
plt.title("Negative Image")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload image
print("Upload a grayscale image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
# Step 2: Read image in grayscale
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
# Step 3: Apply log transformation
img_float = np.float32(img) # Convert to float to avoid log(0) issues
log_transformed = cv2.normalize(np.log1p(img_float), None, 0, 255, cv2.NORM_MINMAX)
log_transformed = np.uint8(log_transformed)
# Step 4: Display original and transformed image
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(log_transformed, cmap='gray')
plt.title("Log Transformed Image")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload an image
print("Upload a grayscale or color image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]
# Step 2: Read the image (convert to grayscale for simplicity)
img = cv2.imread(image_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Step 3: Apply gamma correction

43

gamma = 0.4 # Use gamma < 1 to brighten, > 1 to darken
gamma_corrected = np.array(255 * (gray / 255) ** gamma, dtype='uint8')
# Step 4: Display original and gamma corrected images
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("Original Image")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(gamma_corrected, cmap='gray')
plt.title(f"Gamma Corrected (γ = {gamma})")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import matplotlib.pyplot as plt
from google.colab import files
import numpy as np
# Upload an X-ray image
print("Upload a grayscale X-ray image:")
uploaded = files.upload()
path = list(uploaded.keys())[0]
# Read in grayscale
img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
# Apply negative transformation
negative = 255 - img
# Display the images
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original X-ray")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(negative, cmap='gray')
plt.title("Negative X-ray")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Upload a telescopic image
print("Upload a grayscale astronomical image:")
uploaded = files.upload()
path = list(uploaded.keys())[0]
# Read in grayscale
img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
# Apply log transformation
img_float = np.float32(img)
log_transformed = cv2.normalize(np.log1p(img_float), None, 0, 255, cv2.NORM_MINMAX)
log_transformed = np.uint8(log_transformed)
# Display images
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Astronomical Image")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(log_transformed, cmap='gray')
plt.title("Log Transformed Image")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Upload a photo
print("Upload a grayscale or color image:")
uploaded = files.upload()
path = list(uploaded.keys())[0]
# Read and convert to grayscale
img = cv2.imread(path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Apply gamma correction
gamma = 0.4 # Use gamma < 1 to brighten, > 1 to darken
gamma_corrected = np.array(255 * (gray / 255) ** gamma, dtype='uint8')
# Display results
plt.figure(figsize=(10, 4))

47

plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("Original Image")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(gamma_corrected, cmap='gray')
plt.title(f"Gamma Corrected (γ = {gamma})")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

48

# Step 1: Upload an image
print("Upload a night-time surveillance image:")
uploaded = files.upload()
path = list(uploaded.keys())[0]
# Step 2: Read and convert to grayscale
img = cv2.imread(path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Step 3: Apply contrast stretching
min_val = np.min(gray)
max_val = np.max(gray)
stretched = ((gray - min_val) / (max_val - min_val) * 255).astype('uint8')
# Step 4: Display result
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("Original Low-Light Image")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(stretched, cmap='gray')
plt.title("Contrast Stretched")
plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
# Step 1: Upload a scanned document
print("Upload a scanned grayscale document:")
uploaded = files.upload()
path = list(uploaded.keys())[0]
# Step 2: Read and convert to grayscale
img = cv2.imread(path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Step 3: Apply CLAHE (Adaptive Histogram Equalization)
clahe = cv2.createCLAHE(clipLimit=4.0, tileGridSize=(8, 8))
enhanced = clahe.apply(gray)
# Step 4: Display result
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("Original Document")
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(enhanced, cmap='gray')
plt.title("CLAHE Enhanced")
plt.axis('off')
plt.tight_layout()
plt.show()



